# Generated by Django 5.1.6 on 2025-02-17 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('sms_id', models.IntegerField(blank=True, null=True)),
                ('device', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SmsQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sms_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SmsFailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
                ('sms_id', models.IntegerField(blank=True, null=True)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('device', models.CharField(max_length=50)),
                ('attempts', models.IntegerField(default=1)),
                ('parent_queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='smsapp.smsqueue')),
            ],
        ),
        migrations.CreateModel(
            name='SmsSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sms_id', models.IntegerField(blank=True, null=True)),
                ('device', models.CharField(max_length=50)),
                ('parent_queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='smsapp.smsqueue')),
            ],
        ),
    ]
