# Generated by Django 5.1.6 on 2025-02-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0002_alter_smsfailed_parent_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsfailed',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='smsfailed',
            name='device',
        ),
        migrations.RemoveField(
            model_name='smsfailed',
            name='parent_queue',
        ),
        migrations.RemoveField(
            model_name='smsprocessing',
            name='device',
        ),
        migrations.RemoveField(
            model_name='smsqueue',
            name='status',
        ),
        migrations.RemoveField(
            model_name='smssent',
            name='device',
        ),
        migrations.RemoveField(
            model_name='smssent',
            name='parent_queue',
        ),
    ]
