# Generated by Django 5.1.6 on 2025-02-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0003_remove_smsfailed_attempts_remove_smsfailed_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsqueue',
            name='sms_id',
        ),
    ]
